### PR TITLE
Fix for the performance issue

### PR DESCRIPTION
**Pull request by lucamug**
Fix for the performance issue https://github.com/wking-io/elm-live/issues/167

### CODE REVIEW

**Comment by harrysarson** [comment]
Does this commit not break the CI?

**Comment by wking-io** [comment]
Nope! Those are all just CI tests for the upcoming docs site. They do not relate to the package itself.

**Comment by harrysarson** [comment]
I am seeing this:
```
$ npm test
> elm-live@3.4.0 test /home/travis/build/wking-io/elm-live
> nyc ava './lib/test.js' --cwd './lib' && npm run report
  ✔ Exits if `--no-recover`
  ✔ Passes correct args to `elm make`
  ✔ Spawns `--path-to-elm` instead of `elm` if given
  ✖ Starts elmServe and chokidar with correct config reloads the app when an HTML, JS or CSS static file changes
  ✔ `--open`s the default browser
  ✔ Serves at the specified `--port`
  ✔ Serves on the specified `--host`
  ✖ Serves from the specified `--dir` watches the right files
  ✔ `--pushstate to support client-side routing
  ✔ gets watched paths from the Elm package file
  ✔ --before-build and --after-build work
  ✔ Skips `--before-build` and `--after-build` when empty
  ✔ Informs of `--before-build` and `--after-build` run errors
  ✔ Shouts if `elm` can’t be found (335ms)
  ✔ Prints any other `elm make` error (161ms)
  ✔ Shouts if the `--before-build` or `--after-build` executable can’t be found
  ✔ Prints any other `--before-build` or `--after-build` command error
  ✔ Informs of compile errors (174ms)
  ✔ Redirects elm make stdio (139ms)
  ✔ Watches all `**/*.elm` files in the current directory
  ✔ debounce debounces (203ms)
  2 tests failed
```
at https://travis-ci.org/wking-io/elm-live/builds/536097068.

**Comment by harrysarson** [comment]
Additionally, this pull request seems to break master:
image

**Pull request merged**
