### PR TITLE
exposing the startPage option from elm-serve

### PR DESCRIPTION
**Pull request by DougVonMoser**
How does this look? 

Happy to make whatever changes. 

Thanks

### CODE REVIEW

**Comment by DougVonMoser** [comment]
whoops, i missed something with the -s command. taking a look

**Comment by DougVonMoser** [comment]
Hmm, I can't seem to get -p shorthand for PORT to work either. 

`elm-live src/Main.elm --port=8080 -o` works fine for me, but
`elm-live src/Main.elm -p=8080 -o` still opens on default port 8000.

Peeking at the commander documentation it seems like everything is set up correctly. 

🤔

**Comment by wking-io** [comment]
Yeah it seems none of them work...that is strange. I have never heard this issue so maybe no one uses them haha. Let me know if you find an answer. We may just remove all of them :)

**Comment by wking-io** [comment]
@DougVonMoser Figured it out! so short flags cannot use `=` to assign the values you have to use a space so your command would be `elm-live src/Main.elm -p 8080 -o`

**Pull request merged**
